In [1]:
import pandas as pd
import requests
import json
from sqlalchemy import create_engine
from tmdb_config import API_KEY
from pprint import pprint

# Import csv file
#movie_data = pd.read_csv("bestPic2018Data.csv")
movie_data = pd.read_csv("bestPic2016-2017Data.csv")

#movie_data

In [2]:
#list of movie titles to query
movies = movie_data['movieName']
#movies

In [3]:
# Build the endpoint URL
url = 'https://api.themoviedb.org/3/search/movie?'
api_key = f'api_key={API_KEY}&query='

# set up lists to hold response data:
movie_id = []
genres = []
original_language = []
original_title = []
overview = []
popularity = []
title = []
vote_average = []
vote_count = []

# junk list
junk_list = []

# loop through movie titles, make requests and parse
for movie in movies :
    response = requests.get(url + api_key + movie).json()
    try:
        movie_id.append(response['results'][0]['id'])
        genres.append(response['results'][0]['genre_ids'])
        original_language.append(response['results'][0]['original_language'])
        original_title.append(response['results'][0]['original_title'])
        overview.append(response['results'][0]['overview'])
        popularity.append(response['results'][0]['popularity'])
        title.append(response['results'][0]['title'])
        vote_average.append(response['results'][0]['vote_average'])
        vote_count.append(response['results'][0]['vote_count'])

    except:
        #print(movie, response)
        junk_list.append(movie)

In [97]:
#print(junk_list)
import ast
from pandas.io.json import json_normalize 
url = 'https://api.themoviedb.org/3/genre/movie/list?'
api_key = f'api_key={API_KEY}&language=en-US'
#genres_mapping = []
response = requests.get(url + api_key  ).json()
data = response
df = json_normalize(data, 'genres')
#data.set_index('Locality', inplace=True)
df = df.set_index('id')
#print (df)
# 
# json_str = json.dumps(data)
# data = json.loads(json_str)
# print((data))
print(genres)
genres_cleaned = []
for genre in genres:
    #print(genre)
    genre_name = []
    for i in genre:
        genre_new = {}
        genre_new["id"] = i
        #genre_name.append()
        genre_new["name"] = df.loc[i,'name']
        genre_name.append(genre_new)
    #genre_new = dict(zip("id":genre, "name":genre_name))
    genres_cleaned.append(genre_name)
# print(genres_cleaned)
#(genres_cleaned).replace("'", '"')
print(genres_cleaned)
#genres_data = json.dumps(ast.literal_eval(genres_cleaned))
# genres_clean = json.dumps(genres_cleaned)
# print(genres_clean)
    #[{"id": 28, "name": "Action"}, {"id": 12, "nam.

[[18, 878, 9648], [18], [18, 36, 10752], [80, 18, 53, 37], [18, 36], [35, 18, 10749], [18], [18], [18], [10749, 18], [18, 36], [10752, 28, 18], [9648, 53, 27], [35, 18], [18, 10749], [18, 36], [18, 14, 10749], [80, 18]]
[[{'id': 18, 'name': 'Drama'}, {'id': 878, 'name': 'Science Fiction'}, {'id': 9648, 'name': 'Mystery'}], [{'id': 18, 'name': 'Drama'}], [{'id': 18, 'name': 'Drama'}, {'id': 36, 'name': 'History'}, {'id': 10752, 'name': 'War'}], [{'id': 80, 'name': 'Crime'}, {'id': 18, 'name': 'Drama'}, {'id': 53, 'name': 'Thriller'}, {'id': 37, 'name': 'Western'}], [{'id': 18, 'name': 'Drama'}, {'id': 36, 'name': 'History'}], [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'name': 'Drama'}, {'id': 10749, 'name': 'Romance'}], [{'id': 18, 'name': 'Drama'}], [{'id': 18, 'name': 'Drama'}], [{'id': 18, 'name': 'Drama'}], [{'id': 10749, 'name': 'Romance'}, {'id': 18, 'name': 'Drama'}], [{'id': 18, 'name': 'Drama'}, {'id': 36, 'name': 'History'}], [{'id': 10752, 'name': 'War'}, {'id': 28, 'name': 'Action'}, {'id': 18, 'name': 'Drama'}], [{'id': 9648, 'name': 'Mystery'}, {'id': 53, 'name': 'Thriller'}, {'id': 27, 'name': 'Horror'}], [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'name': 'Drama'}], [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'name': 'Romance'}], [{'id': 18, 'name': 'Drama'}, {'id': 36, 'name': 'History'}], [{'id': 18, 'name': 'Drama'}, {'id': 14, 'name': 'Fantasy'}, {'id': 10749, 'name': 'Romance'}], [{'id': 80, 'name': 'Crime'}, {'id': 18, 'name': 'Drama'}]]

In [98]:
# Making a pass to get more detailed data, have to use ids

# Build the endpoint URL
url = 'https://api.themoviedb.org/3/movie/'
api_key = f'?api_key={API_KEY}&query='

budget = []
production_companies = []
production_countries = []
status = []
tagline = []
release_date = []
revenue = []
runtime = []
spoken_languages = []

# loop through movie ids, make requests and parse
for movie in movie_id :
    response = requests.get(url + str(movie) + api_key).json()
    try:
        budget.append(response['budget'])
        production_companies.append(response['production_companies'])
        production_countries.append(response['production_countries'])
        status.append(response['status'])
        tagline.append(response['tagline'])
        release_date.append(response['release_date'])        
        revenue.append(response['revenue'])
        runtime.append(response['runtime'])
        spoken_languages.append(response['spoken_languages'])
    except:
        #print(movie, response)
        junk_list.append(movie)

In [99]:
#budget

In [100]:
# Making a pass to get cast data, have to use ids

# Build the endpoint URL
url = 'https://api.themoviedb.org/3/movie/'
api_key = f'/credits?api_key={API_KEY}&query='

cast = []
crew = []

# loop through movie ids, make requests and parse
for movie in movie_id :
    response = requests.get(url + str(movie) + api_key).json()
    try:
        cast.append(response['cast'])
        crew.append(response['crew'])
    except:
        #print(movie, response)
        junk_list.append(movie)

In [101]:
#cast

In [102]:
# Making a pass to get keywords data, have to use ids

# Build the endpoint URL
url = 'https://api.themoviedb.org/3/movie/'
api_key = f'/keywords?api_key={API_KEY}&query='

keywords = []

# loop through movie ids, make requests and parse
for movie in movie_id :
    response = requests.get(url + str(movie) + api_key).json()
    try:
        keywords.append(response['keywords'])
    except:
        #print(movie, response)
        junk_list.append(movie)

In [103]:
#keywords

In [104]:
# This Block for sorting through errors
print(genres_cleaned)
#print("Length of Ranks Series: " , len(ranks))
#for junk in junk_list:
#    print(junk)
#    i=movies[movies==junk]
#    print(i.index, i.index[0])
#    ranks = ranks.drop(i.index[0])
#print("Length of Ranks Series: " , len(ranks))

[[{'id': 18, 'name': 'Drama'}, {'id': 878, 'name': 'Science Fiction'}, {'id': 9648, 'name': 'Mystery'}], [{'id': 18, 'name': 'Drama'}], [{'id': 18, 'name': 'Drama'}, {'id': 36, 'name': 'History'}, {'id': 10752, 'name': 'War'}], [{'id': 80, 'name': 'Crime'}, {'id': 18, 'name': 'Drama'}, {'id': 53, 'name': 'Thriller'}, {'id': 37, 'name': 'Western'}], [{'id': 18, 'name': 'Drama'}, {'id': 36, 'name': 'History'}], [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'name': 'Drama'}, {'id': 10749, 'name': 'Romance'}], [{'id': 18, 'name': 'Drama'}], [{'id': 18, 'name': 'Drama'}], [{'id': 18, 'name': 'Drama'}], [{'id': 10749, 'name': 'Romance'}, {'id': 18, 'name': 'Drama'}], [{'id': 18, 'name': 'Drama'}, {'id': 36, 'name': 'History'}], [{'id': 10752, 'name': 'War'}, {'id': 28, 'name': 'Action'}, {'id': 18, 'name': 'Drama'}], [{'id': 9648, 'name': 'Mystery'}, {'id': 53, 'name': 'Thriller'}, {'id': 27, 'name': 'Horror'}], [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'name': 'Drama'}], [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'name': 'Romance'}], [{'id': 18, 'name': 'Drama'}, {'id': 36, 'name': 'History'}], [{'id': 18, 'name': 'Drama'}, {'id': 14, 'name': 'Fantasy'}, {'id': 10749, 'name': 'Romance'}], [{'id': 80, 'name': 'Crime'}, {'id': 18, 'name': 'Drama'}]]

In [94]:
# save data to pandas dataframe
movies_df = pd.DataFrame({
    'title' : title,
    'cast' : cast,
    'crew' : crew,
    'budget' : budget,
    'genres_new' : genres_cleaned,
    'movie_id' : movie_id,
    'keywords' : keywords,
    'original_language' : original_language,
    'original_title' : original_title,
    'overview' : overview,
    'popularity' : popularity,
    'production_companies' : production_companies,
    'production_countries' : production_countries,
    'release_date' : release_date,
    'revenue' : revenue,
    'runtime' : runtime,
    'spoken_languages' : spoken_languages,
    'status' : status,
    'tagline' : tagline,
    'vote_average' : vote_average,
    'vote_count' : vote_count
})
movies_df.tail()
# movies_df.genres

,title,cast,crew,budget,genres_new,movie_id,keywords,original_language,original_title,overview,...,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,vote_average,vote_count
13,Lady Bird,"[{'cast_id': 2, 'character': 'Christine ""Lady ...","[{'credit_id': '5705b7a2c3a3685d4c0008c7', 'de...",10000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",391713,"[{'id': 10683, 'name': 'coming of age'}, {'id'...",en,Lady Bird,A California high school student plans to esca...,...,"[{'id': 93105, 'logo_path': None, 'name': 'IAC...","[{'iso_3166_1': 'US', 'name': 'United States o...",2017-09-08,76858273,94,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Fly Away Home.,7.3,3989
14,Phantom Thread,"[{'cast_id': 2, 'character': 'Reynolds Woodcoc...","[{'credit_id': '57516e2cc3a3686bec0008d4', 'de...",35000000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",400617,"[{'id': 212, 'name': 'london'}, {'id': 1157, '...",en,Phantom Thread,Renowned British dressmaker Reynolds Woodcock ...,...,"[{'id': 178, 'logo_path': None, 'name': 'Ghoul...","[{'iso_3166_1': 'US', 'name': 'United States o...",2017-12-25,47756590,130,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,,7.3,1663
15,The Post,"[{'cast_id': 1, 'character': 'Kay Graham', 'cr...","[{'credit_id': '58c4313ac3a36853360000ff', 'de...",50000000,"[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...",446354,"[{'id': 521, 'name': 'washington d.c.'}, {'id'...",en,The Post,A cover-up that spanned four U.S. Presidents p...,...,"[{'id': 56, 'logo_path': '/cEaxANEisCqeEoRvODv...","[{'iso_3166_1': 'US', 'name': 'United States o...",2017-12-22,174503458,116,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Truth be told,7.0,2566
16,The Shape of Water,"[{'cast_id': 13, 'character': 'Elisa Esposito'...","[{'credit_id': '57cbabe2c3a3686744005cd2', 'de...",19500000,"[{'id': 18, 'name': 'Drama'}, {'id': 14, 'name...",399055,"[{'id': 2106, 'name': 'cold war'}, {'id': 2672...",en,The Shape of Water,"An other-worldly story, set against the backdr...",...,"[{'id': 101082, 'logo_path': None, 'name': 'Do...","[{'iso_3166_1': 'US', 'name': 'United States o...",2017-12-01,194989655,123,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,A Fairy Tale for Troubled Times,7.2,7418
17,"Three Billboards Outside Ebbing, Missouri","[{'cast_id': 0, 'character': 'Mildred Hayes', ...","[{'credit_id': '55f7440cc3a3686d0300b7a9', 'de...",15000000,"[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...",359940,"[{'id': 236, 'name': 'suicide'}, {'id': 570, '...",en,"Three Billboards Outside Ebbing, Missouri",After seven months have passed without a culpr...,...,"[{'id': 2376, 'logo_path': '/yeNoWmSHZfvKsBYuL...","[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...",2017-11-10,158526998,115,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,,8.2,5577

In [95]:
#movies_df.to_csv('2018_best_picture_tmdb.csv', index=False)
movies_df.to_csv('2016_2017_best_picture_tmdb2.csv', index=False)