In [6]:
import pandas as pd
import requests
import json
from sqlalchemy import create_engine
from tmdb_config import API_KEY
from pprint import pprint

# Import csv file
movie_data = pd.read_csv("bestPic2018Data.csv")
#movie_data = pd.read_csv("bestPic2016-2017Data.csv")

#movie_data

,year,ceremony,award,winner,movieName,filmInfo
0,2016,89,Best Picture,1,Arrival,"Shawn Levy, Dan Levine, Aaron Ryder and David ..."
1,2016,89,Best Picture,1,Fences,"Scott Rudin, Denzel Washington and Todd Black,..."
2,2016,89,Best Picture,1,Hacksaw Ridge,"Bill Mechanic and David Permut, Producers"
3,2016,89,Best Picture,1,Hell or High Water,"Carla Hacken and Julie Yorn, Producers"
4,2016,89,Best Picture,1,Hidden Figures,"Donna Gigliotti, Peter Chernin, Jenno Topping,..."
5,2016,89,Best Picture,1,La La Land,"Fred Berger, Jordan Horowitz and Marc Platt, P..."
6,2016,89,Best Picture,1,Lion,"Emile Sherman, Iain Canning and Angie Fielder,..."
7,2016,89,Best Picture,1,Manchester by the Sea,"Matt Damon, Kimberly Steward, Chris Moore, Lau..."
8,2016,89,Best Picture,1,Moonlight,"Adele Romanski, Dede Gardner and Jeremy Kleine..."
9,2017,90,Best Picture,1,Call Me by Your Name,"Peter Spears, Luca Guadagnino, Emilie Georges ..."
10,2017,90,Best Picture,1,Darkest Hour,"Tim Bevan, Eric Fellner, Lisa Bruce, Anthony M..."
11,2017,90,Best Picture,1,Dunkirk,"Emma Thomas and Christopher Nolan, Producers"
12,2017,90,Best Picture,1,Get Out,"Sean McKittrick, Jason Blum, Edward H. Hamm Jr..."
13,2017,90,Best Picture,1,Lady Bird,"Scott Rudin, Eli Bush and Evelyn O'Neill, Prod..."
14,2017,90,Best Picture,1,Phantom Thread,"JoAnne Sellar, Paul Thomas Anderson, Megan Ell..."
15,2017,90,Best Picture,1,The Post,"Amy Pascal, Steven Spielberg and Kristie Macos..."
16,2017,90,Best Picture,1,The Shape of Water,"Guillermo del Toro and J. Miles Dale, Producers"
17,2017,90,Best Picture,1,"Three Billboards outside Ebbing, Missouri","Graham Broadbent, Pete Czernin and Martin McDo..."

In [7]:
#list of movie titles to query
movies = movie_data['movieName']
#movies

In [8]:
# Build the endpoint URL
url = 'https://api.themoviedb.org/3/search/movie?'
api_key = f'api_key={API_KEY}&query='

# set up lists to hold response data:
movie_id = []
genres = []
original_language = []
original_title = []
overview = []
popularity = []
title = []
vote_average = []
vote_count = []

# junk list
junk_list = []

# loop through movie titles, make requests and parse
for movie in movies :
    response = requests.get(url + api_key + movie).json()
    try:
        movie_id.append(response['results'][0]['id'])
        genres.append(response['results'][0]['genre_ids'])
        original_language.append(response['results'][0]['original_language'])
        original_title.append(response['results'][0]['original_title'])
        overview.append(response['results'][0]['overview'])
        popularity.append(response['results'][0]['popularity'])
        title.append(response['results'][0]['title'])
        vote_average.append(response['results'][0]['vote_average'])
        vote_count.append(response['results'][0]['vote_count'])

    except:
        #print(movie, response)
        junk_list.append(movie)

In [9]:
#print(junk_list)

In [10]:
# Making a pass to get more detailed data, have to use ids

# Build the endpoint URL
url = 'https://api.themoviedb.org/3/movie/'
api_key = f'?api_key={API_KEY}&query='

budget = []
production_companies = []
production_countries = []
status = []
tagline = []
release_date = []
revenue = []
runtime = []
spoken_languages = []

# loop through movie ids, make requests and parse
for movie in movie_id :
    response = requests.get(url + str(movie) + api_key).json()
    try:
        budget.append(response['budget'])
        production_companies.append(response['production_companies'])
        production_countries.append(response['production_countries'])
        status.append(response['status'])
        tagline.append(response['tagline'])
        release_date.append(response['release_date'])        
        revenue.append(response['revenue'])
        runtime.append(response['runtime'])
        spoken_languages.append(response['spoken_languages'])
    except:
        #print(movie, response)
        junk_list.append(movie)

In [6]:
#budget

In [11]:
# Making a pass to get cast data, have to use ids

# Build the endpoint URL
url = 'https://api.themoviedb.org/3/movie/'
api_key = f'/credits?api_key={API_KEY}&query='

cast = []
crew = []

# loop through movie ids, make requests and parse
for movie in movie_id :
    response = requests.get(url + str(movie) + api_key).json()
    try:
        cast.append(response['cast'])
        crew.append(response['crew'])
    except:
        #print(movie, response)
        junk_list.append(movie)

In [8]:
#cast

In [12]:
# Making a pass to get keywords data, have to use ids

# Build the endpoint URL
url = 'https://api.themoviedb.org/3/movie/'
api_key = f'/keywords?api_key={API_KEY}&query='

keywords = []

# loop through movie ids, make requests and parse
for movie in movie_id :
    response = requests.get(url + str(movie) + api_key).json()
    try:
        keywords.append(response['keywords'])
    except:
        #print(movie, response)
        junk_list.append(movie)

In [10]:
#keywords

In [11]:
# This Block for sorting through errors

#print("Length of Ranks Series: " , len(ranks))
#for junk in junk_list:
#    print(junk)
#    i=movies[movies==junk]
#    print(i.index, i.index[0])
#    ranks = ranks.drop(i.index[0])
#print("Length of Ranks Series: " , len(ranks))

In [13]:
# save data to pandas dataframe
movies_df = pd.DataFrame({
    'title' : title,
    'cast' : cast,
    'crew' : crew,
    'budget' : budget,
    'genres' : genres,
    'movie_id' : movie_id,
    'keywords' : keywords,
    'original_language' : original_language,
    'original_title' : original_title,
    'overview' : overview,
    'popularity' : popularity,
    'production_companies' : production_companies,
    'production_countries' : production_countries,
    'release_date' : release_date,
    'revenue' : revenue,
    'runtime' : runtime,
    'spoken_languages' : spoken_languages,
    'status' : status,
    'tagline' : tagline,
    'vote_average' : vote_average,
    'vote_count' : vote_count
})
movies_df.head()

,cast,crew,budget,genres,movie_id,keywords,original_language,original_title,overview,popularity,...,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,"[{'cast_id': 2, 'character': 'Dr. Louise Banks...","[{'credit_id': '55219ea292514170960018df', 'de...",47000000,"[18, 878, 9648]",329865,"[{'id': 1612, 'name': 'spacecraft'}, {'id': 59...",en,Arrival,Taking place after alien crafts land around th...,22.192,...,"[{'iso_3166_1': 'US', 'name': 'United States o...",2016-11-10,203388186,116,"[{'iso_639_1': 'zh', 'name': '普通话'}, {'iso_639...",Released,Why are they here?,Arrival,7.4,10588
1,"[{'cast_id': 3, 'character': 'Troy Maxson', 'c...","[{'credit_id': '57150d48925141387d006150', 'de...",24000000,[18],393457,"[{'id': 1480, 'name': 'baseball'}, {'id': 1543...",en,Fences,"In 1950s Pittsburgh, a frustrated African-Amer...",11.129,...,"[{'iso_3166_1': 'CA', 'name': 'Canada'}, {'iso...",2016-12-16,64414761,139,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"Some people build fences to keep people out, a...",Fences,6.8,1506
2,"[{'cast_id': 3, 'character': 'Desmond T. Doss'...","[{'credit_id': '5925ff7b9251413ba001460f', 'de...",40000000,"[18, 36, 10752]",324786,"[{'id': 233, 'name': 'japan'}, {'id': 1956, 'n...",en,Hacksaw Ridge,"WWII American Army Medic Desmond T. Doss, who ...",20.753,...,"[{'iso_3166_1': 'AU', 'name': 'Australia'}, {'...",2016-10-07,175302354,139,"[{'iso_639_1': 'ja', 'name': '日本語'}, {'iso_639...",Released,One of the greatest heroes in American history...,Hacksaw Ridge,8.1,6784
3,"[{'cast_id': 3, 'character': 'Marcus Hamilton'...","[{'credit_id': '5547ee489251415605000103', 'de...",12000000,"[80, 18, 53, 37]",338766,"[{'id': 1333, 'name': 'desperation'}, {'id': 2...",en,Hell or High Water,A divorced dad and his ex-con brother resort t...,14.927,...,"[{'iso_3166_1': 'US', 'name': 'United States o...",2016-08-12,37589296,102,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Blood always follows money.,Hell or High Water,7.3,2508
4,"[{'cast_id': 1, 'character': 'Katherine G. Joh...","[{'credit_id': '56b40025c3a36806ec0035f0', 'de...",25000000,"[18, 36]",381284,"[{'id': 1432, 'name': 'nasa'}, {'id': 4411, 'n...",en,Hidden Figures,"The untold story of Katherine G. Johnson, Doro...",18.626,...,"[{'iso_3166_1': 'US', 'name': 'United States o...",2016-12-10,230698791,127,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"Meet the women you don't know, behind the miss...",Hidden Figures,8.0,4859

In [14]:
#movies_df.to_csv('2018_best_picture_tmdb.csv', index=False)
movies_df.to_csv('2016_2017_best_picture_tmdb.csv', index=False)