In [1]:
import pandas as pd
import requests
import json
from sqlalchemy import create_engine
from tmdb_config import API_KEY
from pprint import pprint

# Import csv file
movie_data = pd.read_csv("bestPic2018Data.csv")
#movie_data

In [2]:
#list of movie titles to query
movies = movie_data['movieName']
#movies

In [3]:
# Build the endpoint URL
url = 'https://api.themoviedb.org/3/search/movie?'
api_key = f'api_key={API_KEY}&query='

# set up lists to hold response data:
movie_id = []
genres = []
original_language = []
original_title = []
overview = []
popularity = []
title = []
vote_average = []
vote_count = []

# junk list
junk_list = []

# loop through movie titles, make requests and parse
for movie in movies :
    response = requests.get(url + api_key + movie).json()
    try:
        movie_id.append(response['results'][0]['id'])
        genres.append(response['results'][0]['genre_ids'])
        original_language.append(response['results'][0]['original_language'])
        original_title.append(response['results'][0]['original_title'])
        overview.append(response['results'][0]['overview'])
        popularity.append(response['results'][0]['popularity'])
        title.append(response['results'][0]['title'])
        vote_average.append(response['results'][0]['vote_average'])
        vote_count.append(response['results'][0]['vote_count'])

    except:
        #print(movie, response)
        junk_list.append(movie)

In [4]:
#print(junk_list)

In [5]:
# Making a pass to get more detailed data, have to use ids

# Build the endpoint URL
url = 'https://api.themoviedb.org/3/movie/'
api_key = f'?api_key={API_KEY}&query='

budget = []
production_companies = []
production_countries = []
status = []
tagline = []
release_date = []
revenue = []
runtime = []
spoken_languages = []

# loop through movie ids, make requests and parse
for movie in movie_id :
    response = requests.get(url + str(movie) + api_key).json()
    try:
        budget.append(response['budget'])
        production_companies.append(response['production_companies'])
        production_countries.append(response['production_countries'])
        status.append(response['status'])
        tagline.append(response['tagline'])
        release_date.append(response['release_date'])        
        revenue.append(response['revenue'])
        runtime.append(response['runtime'])
        spoken_languages.append(response['spoken_languages'])
    except:
        #print(movie, response)
        junk_list.append(movie)

In [6]:
#budget

In [7]:
# Making a pass to get cast data, have to use ids

# Build the endpoint URL
url = 'https://api.themoviedb.org/3/movie/'
api_key = f'/credits?api_key={API_KEY}&query='

cast = []
crew = []

# loop through movie ids, make requests and parse
for movie in movie_id :
    response = requests.get(url + str(movie) + api_key).json()
    try:
        cast.append(response['cast'])
        crew.append(response['crew'])
    except:
        #print(movie, response)
        junk_list.append(movie)

In [8]:
#cast

In [9]:
# Making a pass to get keywords data, have to use ids

# Build the endpoint URL
url = 'https://api.themoviedb.org/3/movie/'
api_key = f'/keywords?api_key={API_KEY}&query='

keywords = []

# loop through movie ids, make requests and parse
for movie in movie_id :
    response = requests.get(url + str(movie) + api_key).json()
    try:
        keywords.append(response['keywords'])
    except:
        #print(movie, response)
        junk_list.append(movie)

In [10]:
#keywords

In [11]:
# This Block for sorting through errors

#print("Length of Ranks Series: " , len(ranks))
#for junk in junk_list:
#    print(junk)
#    i=movies[movies==junk]
#    print(i.index, i.index[0])
#    ranks = ranks.drop(i.index[0])
#print("Length of Ranks Series: " , len(ranks))

In [13]:
# save data to pandas dataframe
movies_df = pd.DataFrame({
    'cast' : cast,
    'crew' : crew,
    'budget' : budget,
    'genres' : genres,
    'movie_id' : movie_id,
    'keywords' : keywords,
    'original_language' : original_language,
    'original_title' : original_title,
    'overview' : overview,
    'popularity' : popularity,
    'production_companies' : production_companies,
    'production_countries' : production_countries,
    'release_date' : release_date,
    'revenue' : revenue,
    'runtime' : runtime,
    'spoken_languages' : spoken_languages,
    'status' : status,
    'tagline' : tagline,
    'title' : title,
    'vote_average' : vote_average,
    'vote_count' : vote_count
})
movies_df.head()

,cast,crew,budget,genres,movie_id,keywords,original_language,original_title,overview,popularity,...,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,"[{'cast_id': 0, 'character': 'King Tâ€™Challa / ...","[{'credit_id': '597357339251411ece0258ef', 'de...",200000000,"[28, 12, 14, 878]",284054,"[{'id': 409, 'name': 'africa'}, {'id': 9715, '...",en,Black Panther,King T'Challa returns home from America to the...,59.895,...,"[{'iso_3166_1': 'US', 'name': 'United States o...",2018-02-13,1346739107,134,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Long live the king.,Black Panther,7.4,12818
1,"[{'cast_id': 11, 'character': 'Ron Stallworth'...","[{'credit_id': '5a0ea98ac3a368628c00a7cd', 'de...",15000000,"[80, 18]",487558,"[{'id': 529, 'name': 'ku klux klan'}, {'id': 8...",en,BlacKkKlansman,"Colorado Springs, late 1970s. Ron Stallworth, ...",25.982,...,"[{'iso_3166_1': 'US', 'name': 'United States o...",2018-07-30,48686605,135,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Infiltrate hate.,BlacKkKlansman,7.6,3363
2,"[{'cast_id': 1, 'character': 'Freddie Mercury'...","[{'credit_id': '5ab9ff039251414d3101091c', 'de...",52000000,"[18, 10402]",424694,"[{'id': 212, 'name': 'london'}, {'id': 237, 'n...",en,Bohemian Rhapsody,"Singer Freddie Mercury, guitarist Brian May, d...",46.137,...,"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...",2018-10-24,894027543,135,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Fearless lives forever,Bohemian Rhapsody,8.1,8141
3,"[{'cast_id': 2, 'character': 'Queen Anne', 'cr...","[{'credit_id': '5686461bc3a36828f501471f', 'de...",15000000,"[18, 36, 35]",375262,"[{'id': 1025, 'name': 'great britain'}, {'id':...",en,The Favourite,"England, early 18th century. The close relatio...",26.588,...,"[{'iso_3166_1': 'IE', 'name': 'Ireland'}, {'is...",2018-11-23,82124805,120,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,,The Favourite,7.6,2291
4,"[{'cast_id': 2, 'character': 'Frank ""Tony Lip""...","[{'credit_id': '5a209ba1925141032c099ee4', 'de...",23000000,"[18, 35]",490132,"[{'id': 237, 'name': 'gay'}, {'id': 531, 'name...",en,Green Book,"Tony Lip, a bouncer in 1962, is hired to drive...",31.321,...,"[{'iso_3166_1': 'US', 'name': 'United States o...",2018-11-16,319700000,130,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Inspired by a True Friendship,Green Book,8.3,3873

In [14]:
movies_df.to_csv('2018_best_picture_tmdb.csv', index=False)