In [1]:
import io, time, json
import requests
from bs4 import BeautifulSoup
import matplotlib.pyplot as plt
import seaborn as sns
import json
import sklearn
from tensorflow.keras.utils import to_categorical
import warnings; warnings.simplefilter('ignore')
%matplotlib inline

In [2]:
# Grabbing the nominees to get latest years data
def retrieve_html(url):
    """
    Return the raw HTML at the specified URL.

    Args:
        url (string): 

    Returns:
        result: dict, movie name as key, movie information as value
    """
    # remember to use browser header here, or cannot retrieve full data from the website
    headers = {
        'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36'}
    response = requests.get(url, headers = headers)
    html = response.content
    soup = BeautifulSoup(html,'lxml')

    result = {}
    for item in soup.find_all('div', {'class':'result-subgroup subgroup-awardcategory-chron'}):
        try:
            award_title = item.find('div',{'class':'result-subgroup-title'}).find('a',{'class':'nominations-link'}).contents[0]
            if award_title == 'ACTOR IN A SUPPORTING ROLE':
                sub_groups = item.find_all('div',{'class':'result-details awards-result-actingorsimilar'})
                for sub in sub_groups:
                    sub_result = {}
                    film_title = sub.find('div',{'class':'awards-result-film-title'}).find('a',{'class':'nominations-link'}).contents[0]
                    is_winner = 1
                    actor = sub.find('div',{'class':'awards-result-nominationstatement'}).find('a',{'class':'nominations-link'}).contents[0]           
                    sub_result['film_title'] = film_title
                    sub_result['is_winner'] = is_winner
                    sub_result['actor'] = actor
                    result[film_title] = sub_result
        except Exception:
            pass
    return result

In [3]:
# data of year 2016
best_2016 = retrieve_html('http://awardsdatabase.oscars.org/Search/GetResults?query=%7B%22AwardShowFrom%22:89,%22Sort%22:%223-Award%20Category-Chron%22,%22Search%22:%22Basic%22%7D')

# data of year 2017
best_2017 = retrieve_html('http://awardsdatabase.oscars.org/Search/GetResults?query=%7B%22AwardShowFrom%22:90,%22Sort%22:%223-Award%20Category-Chron%22,%22Search%22:%22Basic%22%7D')

# data of year 2018
best_2018 = retrieve_html('http://awardsdatabase.oscars.org/Search/GetResults?query=%7B%22AwardShowFrom%22:91,%22Sort%22:%223-Award%20Category-Chron%22,%22Search%22:%22Basic%22%7D')
#best_2016

In [4]:
# Load Data
import numpy as np
import pandas as pd
# read from award
df_awards = pd.read_csv('database.csv', skiprows = 1, names=['year','ceremony','award','winner','name','film'])
df_movies = pd.read_csv('movies.csv')
df_credits = pd.read_csv('credits.csv')

In [ ]:
#View data
#print(df_awards.head(10))
#print("")
#print(df_movies.head(10))
#print("")
#print(df_credits.head())

In [ ]:
# Testing
# Get list of awards to make sure we include all the right ones
#df_awards.award.unique()

In [5]:
# this keeps popping up 2016 3 times and 2017 2 times. clean this part up.
# append the data we scrapped to the df_awards
data=[]
for k,v in best_2016.items():
    row = []
    row.append(['2016', 89, 'Best Actor in a Supporting Role', v['is_winner'], v['actor'], v['film_title']])
    data.append(row[0])

    
# pass the column name to the columns!!! Or there will be a runtime error
df_awards=df_awards.append(pd.DataFrame(data,columns=['year','ceremony','award','winner','name','film']),ignore_index=True)

data_=[]
for k,v in best_2017.items():
    row = []
    row.append(['2017', 90, 'Best Actor in a Supporting Role', v['is_winner'], v['actor'], v['film_title']])
    data.append(row[0])

df_awards=df_awards.append(pd.DataFrame(data,columns=['year','ceremony','award','winner','name','film']),ignore_index=True)

data_=[]
for k,v in best_2018.items():
    row = []
    row.append(['2018', 91, 'Best Actor in a Supporting Role', v['is_winner'], v['actor'], v['film_title']])
    data.append(row[0])

df_awards=df_awards.append(pd.DataFrame(data,columns=['year','ceremony','award','winner','name','film']),ignore_index=True)
df_awards

,year,ceremony,award,winner,name,film
0,1928,1,Actor,NaN,Richard Barthelmess,The Noose
1,1928,1,Actor,1.0,Emil Jannings,The Last Command
2,1928,1,Actress,NaN,Louise Dresser,A Ship Comes In
3,1928,1,Actress,1.0,Janet Gaynor,7th Heaven
4,1928,1,Actress,NaN,Gloria Swanson,Sadie Thompson
5,1928,1,Art Direction,NaN,Rochus Gliese,Sunrise
6,1928,1,Art Direction,1.0,William Cameron Menzies,The Dove; Tempest
7,1928,1,Art Direction,NaN,Harry Oliver,7th Heaven
8,1928,1,Cinematography,NaN,George Barnes,The Devil Dancer; The Magic Flame; Sadie Thompson
9,1928,1,Cinematography,1.0,Charles Rosher,Sunrise
10,1928,1,Cinematography,1.0,Karl Struss,Sunrise
11,1928,1,Directing (Comedy Picture),1.0,Lewis Milestone,Two Arabian Knights
12,1928,1,Directing (Comedy Picture),NaN,Ted Wilde,Speedy
13,1928,1,Directing (Dramatic Picture),1.0,Frank Borzage,7th Heaven
14,1928,1,Directing (Dramatic Picture),NaN,Herbert Brenon,Sorrell and Son
15,1928,1,Directing (Dramatic Picture),NaN,King Vidor,The Crowd
16,1928,1,Engineering Effects,NaN,Ralph Hammeras,NaN
17,1928,1,Engineering Effects,1.0,Roy Pomeroy,Wings
18,1928,1,Engineering Effects,NaN,Nugent Slaughter,NaN
19,1928,1,Outstanding Picture,NaN,The Caddo Company,The Racket
20,1928,1,Outstanding Picture,NaN,Fox,7th Heaven
21,1928,1,Outstanding Picture,1.0,Paramount Famous Lasky,Wings
22,1928,1,Unique and Artistic Picture,1.0,Fox,Sunrise
23,1928,1,Unique and Artistic Picture,NaN,Metro-Goldwyn-Mayer,The Crowd
24,1928,1,Unique and Artistic Picture,NaN,Paramount Famous Lasky,Chang
25,1928,1,Writing (Adaptation),NaN,Alfred Cohn,The Jazz Singer
26,1928,1,Writing (Adaptation),NaN,Anthony Coldeway,Glorious Betsy
27,1928,1,Writing (Adaptation),1.0,Benjamin Glazer,7th Heaven
28,1928,1,Writing (Original Story),NaN,Lajos Biro,The Last Command
29,1928,1,Writing (Original Story),1.0,Ben Hecht,Underworld
...,...,...,...,...,...,...
9962,2015,88,Honorary Award,1.0,Spike Lee,NaN
9963,2015,88,Honorary Award,1.0,Gena Rowlands,NaN
9964,2016,89,Best Actor in a Supporting Role,1.0,Mahershala Ali,Moonlight
9965,2016,89,Best Actor in a Supporting Role,1.0,Jeff Bridges,Hell or High Water
9966,2016,89,Best Actor in a Supporting Role,1.0,Lucas Hedges,Manchester by the Sea
9967,2016,89,Best Actor in a Supporting Role,1.0,Dev Patel,Lion
9968,2016,89,Best Actor in a Supporting Role,1.0,Michael Shannon,Nocturnal Animals
9969,2016,89,Best Actor in a Supporting Role,1.0,Mahershala Ali,Moonlight
9970,2016,89,Best Actor in a Supporting Role,1.0,Jeff Bridges,Hell or High Water
9971,2016,89,Best Actor in a Supporting Role,1.0,Lucas Hedges,Manchester by the Sea
9972,2016,89,Best Actor in a Supporting Role,1.0,Dev Patel,Lion
9973,2016,89,Best Actor in a Supporting Role,1.0,Michael Shannon,Nocturnal Animals
9974,2017,90,Best Actor in a Supporting Role,1.0,Willem Dafoe,The Florida Project
9975,2017,90,Best Actor in a Supporting Role,1.0,Sam Rockwell,"Three Billboards outside Ebbing, Missouri"
9976,2017,90,Best Actor in a Supporting Role,1.0,Richard Jenkins,The Shape of Water
9977,2017,90,Best Actor in a Supporting Role,1.0,Christopher Plummer,All the Money in the World
9978,2016,89,Best Actor in a Supporting Role,1.0,Mahershala Ali,Moonlight
9979,2016,89,Best Actor in a Supporting Role,1.0,Jeff Bridges,Hell or High Water
9980,2016,89,Best Actor in a Supporting Role,1.0,Lucas Hedges,Manchester by the Sea
9981,2016,89,Best Actor in a Supporting Role,1.0,Dev Patel,Lion
9982,2016,89,Best Actor in a Supporting Role,1.0,Michael Shannon,Nocturnal Animals
9983,2017,90,Best Actor in a Supporting Role,1.0,Willem Dafoe,The Florida Project
9984,2017,90,Best Actor in a Supporting Role,1.0,Sam Rockwell,"Three Billboards outside Ebbing, Missouri"
9985,2017,90,Best Actor in a Supporting Role,1.0,Richard Jenkins,The Shape of Water
9986,2017,90,Best Actor in a Supporting Role,1.0,Christopher Plummer,All the Money in the World
9987,2018,91,Best Actor in a Supporting Role,1.0,Mahershala Ali,Green Book
9988,2018,91,Best Actor in a Supporting Role,1.0,Adam Driver,BlacKkKlansman
9989,2018,91,Best Actor in a Supporting Role,1.0,Sam Elliott,A Star Is Born
9990,2018,91,Best Actor in a Supporting Role,1.0,Richard E. Grant,Can You Ever Forgive Me?
9991,2018,91,Best Actor in a Supporting Role,1.0,Sam Rockwell,Vice

In [ ]:
# Data Manipulation
#Joining the credits and movies dataframes
if 'title' in df_credits.columns: 
  df_credits = df_credits.drop('title',axis=1) 
df_credits_movies = df_credits.set_index('movie_id').join(df_movies.set_index('id'))

In [ ]:
#df_credits_movies.dtypes
# Reset the data types and get the earliest date of release_date
df_credits_movies['release_date'] = pd.to_datetime(df_credits_movies['release_date'])
#get the earliest release date from the dataset
min_year = min(df_credits_movies['release_date']) #1916-09-04
max_year = max(df_credits_movies['release_date']) #2017-02-03

In [ ]:
# Select movies that are in 'Best Actor in a Supporting Role' categories -> df_picture_awards
#join df_credits_movies and df_awards by movie name (df_credits_movies.title = df_awards.movieName)

df_picture_awards = df_awards.loc[df_awards['award'].isin(['Best Actor in a Supporting Role'])]
df_picture_awards.reset_index(drop = True, inplace = True)
df_credits_movies = df_credits_movies.loc[df_credits_movies['status'].isin(['Released'])]

In [ ]:
# Replace all the null value in ‘winner’ column with 1
# df_picture_awards['winner'].isnull().sum()
df_picture_awards['winner'].fillna(1,inplace = True)

In [ ]:
# join df_picture_awards with df_credits_movies
#cleaning names/punctuation
import re
actorName = [re.sub(r'[^\w\s]','',x) for x in df_picture_awards['name'].str.lower().str.strip().values]
title = [re.sub(r'[^\w\s]','',x) for x in df_credits_movies['title'].str.lower().str.strip().values]
#then, change the title in the movie to lower case
df_picture_awards.loc[:,'actor'] = actorName #change the string to lower case
df_credits_movies.loc[:,'actor']= title
# check the dataframe, we can see the string in best_actor now is valid
print(df_picture_awards)

In [ ]:
# join the two tables, merge the data
df = df_picture_awards.merge(df_credits_movies, left_on='best_actor', right_on='best_actor', how='right')
df = df.reset_index(drop=True)
#drop the columns from award table
df.drop('homepage',axis = 1, inplace = True)
df.drop('year',axis = 1, inplace = True)
df.drop('award',axis = 1, inplace = True)
df.drop('name',axis = 1, inplace = True)
df.drop('film',axis = 1, inplace = True)
df.drop('ceremony',axis = 1, inplace = True)
df['winner'].fillna(0,inplace=True) #fill NA with 0

In [ ]:
# We will choose the under-sampling by sampling from the 0-labeled data. 
# We need to first get a subset of nominated data, then sample from the non-nominated data, 
# and finally append the sampled data to the subset of nominated data.
sns.countplot(x='winner', data = df)

In [ ]:
#Get the number of 0 labeled data, and the number of 1 labeled data
print(len(df.loc[df['winner'] == 0])) #4590
print(len(df.loc[df['winner'] == 1])) #205

In [ ]:
#balance the data
df_subset_0 = df.loc[df['winner'] == 0]
df_subset_1 = df.loc[df['winner'] == 1]

df_subset_0.drop('winner',axis=1,inplace=True)
df_subset_1.drop('winner',axis=1,inplace=True)

#sample with replacement
df_subset_0 = df_subset_0.sample(400) 
df_subset = pd.concat([df_subset_0,df_subset_1],ignore_index = True)
df_new = df_subset.merge(df_picture_awards, left_on = 'best_actor', right_on = 'best_actor', how = 'left')
df_new = df_new.fillna(0)

In [ ]:
print(len(df_new))

In [ ]:
sns.countplot(x='winner', data = df_new)

In [ ]:
#check number of null values in the dataset
df_new.isnull().sum()

In [ ]:
#Exploratory Data Analysis

# check the data types and select numeric variables
df_new.dtypes

In [ ]:
# correlation analysis
g = sns.heatmap(df_new[['budget','popularity','revenue','runtime','vote_average','vote_count']].corr(),cmap='RdYlGn',annot=True)

In [ ]:
# Density Curve
# budget
budget0 = df_new[df_new['winner'] == 0]['budget']
budget1 = df_new[df_new['winner'] == 1]['budget']

g = sns.kdeplot(budget0, legend = True, shade=True, color='r',label = 'non-nominated')
g = sns.kdeplot(budget1, legend = True, shade=True, color='b', label = 'nonminated')

In [ ]:
# revenue
# density curve
revenue0 = df_new[df_new['winner'] == 0]['revenue']
revenue1 = df_new[df_new['winner'] == 1]['revenue']

g = sns.kdeplot(revenue0, legend = True, shade=True, color='r',label = 'non-nominated')
g = sns.kdeplot(revenue1, legend = True, shade=True, color='b', label = 'nonminated')

In [ ]:
# vote count
vc0 = df_new[df_new['winner'] == 0]['vote_count']
vc1 = df_new[df_new['winner'] == 1]['vote_count']

g = sns.kdeplot(vc0, legend = True, shade=True, color='r',label = 'non-nominated')
g = sns.kdeplot(vc1, legend = True, shade=True, color='b', label = 'nonminated')

In [ ]:
# vote average
va0 = df_new[df_new['winner'] == 0]['vote_average']
va1 = df_new[df_new['winner'] == 1]['vote_average']

g = sns.kdeplot(va0, legend = True, shade=True, color='r',label = 'non-nominated')
g = sns.kdeplot(va1, legend = True, shade=True, color='b', label = 'nonminated')

In [ ]:
# popularity
popularity0 = df_new[df_new['winner'] == 0]['popularity']
popularity1 = df_new[df_new['winner'] == 1]['popularity']

g = sns.kdeplot(popularity0, legend = True, shade=True, color='r',label = 'non-nominated')
g = sns.kdeplot(popularity1, legend = True, shade=True, color='b', label = 'nonminated')

In [ ]:
#runtime
runtime0 = df_new[df_new['winner'] == 0]['runtime']
runtime1 = df_new[df_new['winner'] == 1]['runtime']

g = sns.kdeplot(runtime0, legend = True, shade=True, color='r', label = 'non-nominated')
g = sns.kdeplot(runtime1, legend = True, shade=True, color='b', label = 'nonminated')

In [ ]:
#genres
#clean the data
genres_name0 = {}
genres_name1 = {}
genres_set = set()
for i in range(len(df_new)):
    genres = json.loads(df_new.loc[i,'genres'])
    for it in genres:
        genres_set.add(it['name'])
        if df_new.loc[i,'winner'] == 0:
            if it['name'] not in genres_name0:
                genres_name0[it['name']] = 1
            else:
                genres_name0[it['name']] += 1
        if df_new.loc[i,'winner'] == 1:
            if it['name'] not in genres_name1:
                genres_name1[it['name']] = 1
            else:
                genres_name1[it['name']] += 1

genres_array0=[]
genres_array1=[]
for g in genres_set:
    if g in genres_name0:
        genres_array0.append(genres_name0[g])
    else:
        genres_array0.append(0)
    if g in genres_name1:
        genres_array1.append(genres_name1[g])
    else:
        genres_array1.append(0)


        
genres_all = []
genres_all.append(np.array(genres_array0)/sum(genres_array0))
genres_all.append(np.array(genres_array1)/sum(genres_array1))

In [ ]:
df_genres = pd.DataFrame(genres_all, columns=list(genres_set))
print(df_genres.head())

In [ ]:
# draw stacked bar chart
N = len(df_genres.columns)
ind = np.arange(N)
width = 0.45

plt.figure(figsize=(20,10))
p1 = plt.bar(ind, df_genres.loc[[0]].values[0], width, color='#d62728')
p2 = plt.bar(ind, df_genres.loc[[1]].values[0], width, bottom=df_genres.loc[[0]].values[0])


plt.ylabel('percentage (#genres/#movies)')
plt.title('Percentage by genres and nominations')
plt.xticks(ind,df_genres.columns)
plt.legend((p1[0],p2[0]),('Non-nominees','nominees'))

In [ ]:
# Feature Engineering
# Since many columns such as “crew”, “cast” contain information in json format, we need to extract useful information from the columns and then perform one hot encoding.
# We will transform our dataset into a all numeric matrix so that we can feed the data into our machine learning model.
# To look at the structure of column (eg.”cast”), we can use: df.loc[0,’cast’]
import json
def feature_engineering(column_name, df, json_name):
    """
    Args:
        column_name: the column name in the dataframe that contains a json file that needs to conduct feature engineering on
        df: dataframe that perform feature engineering on
        json_name: name in the json file that we want to extract
    
    Returns: new dataframe after feature engineering
    """
    
    name = {}

    for item in df[column_name]:
        group = json.loads(item)
        for it in group:
            if it[json_name] not in name:
                name[it[json_name]] = 1
            else:
                name[it[json_name]] += 1
    
    final = {}
    index = 0
    for k,v in name.items():
        if v > 1:
            final[k] = index
            index += 1
    np_item = np.zeros((len(df),len(final)))
    item_dict = {}
    row = 0
    for item in df[column_name]:
        group = json.loads(item)
        for it in group:
            if it[json_name] in final:
                index = final[it[json_name]]
                np_item[row][index] = 1
        row += 1

    df_item = pd.DataFrame(np_item, columns = list(final.keys()))
    df_output = pd.concat([df,df_item],axis = 1)
    
    return df_output

In [ ]:
df2 = feature_engineering("cast", df_new, "name")
df2 = df2.drop('cast', axis = 1) #drop the column after feature engineering

In [ ]:
# director
crew_name = {}

for item in df2['crew']:
    crew = json.loads(item)
    for it in crew:
        if it['job'] == 'Director':
            if it['name'] not in crew_name:
                crew_name[it['name']] = 1
            else:
                crew_name[it['name']]+=1


# set the appear tims for actors
final_crew = {}
index = 0
for k,v in crew_name.items():
    if v > 0:
        final_crew[k] = index
        index += 1
# print(len(final_crew))

np_crew = np.zeros((len(df2), len(final_crew)))
row = 0
for item in df2['crew']:
    crew = json.loads(item)
    for it in crew:
        if it['job'] == 'Director':
            if it['name'] in final_crew:
                index = final_crew[it['name']]
                np_crew[row][index] = 1
    row += 1

df_crew = pd.DataFrame(np_crew, columns = list(final_crew.keys()))
            
df3 = pd.concat([df2, df_crew], axis = 1)
# print(df.shape)

In [ ]:
df3=df3.drop(['crew'],axis=1)
#genres
df4 = feature_engineering("genres", df3, "name")
df4 = df4.drop(['genres'], axis = 1)
#keywords
df5 = feature_engineering('keywords', df4, 'name')
df5 = df5.drop(['keywords'], axis = 1)
#production_companies
df6 = feature_engineering('production_companies',df5,'name')
df6 = df6.drop(['production_companies'],axis=1)
#production_countries
df7 = feature_engineering('production_countries',df6,'name')
df7 = df7.drop(['production_countries'],axis=1)
#spoken_languages
df8 = feature_engineering('spoken_languages',df7,'iso_639_1')
df8 = df8.drop(['spoken_languages'],axis=1)
# drop the columns not used
df_clean = df8.drop(["best_actor","original_title","overview","tagline",'title','original_language','status','release_date','name','film','award'],axis=1)

In [ ]:
df_clean.head()

In [ ]:
# Model Training
# split
X = df_clean[df_clean.columns.difference(['winner'])]
# X = StandardScaler().fit_transform(X)
y = df_clean['winner']
from sklearn.model_selection import train_test_split
# test_size: what proportion of original data is used for test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/5.0, random_state=0)

In [ ]:
from sklearn.decomposition import PCA
pca = PCA(0.95)
fit = pca.fit(X_train)

X_train = pca.transform(X_train)
X_test = pca.transform(X_test)
# pca = PCA(n_components = 3)
# fit = pca.fit_transform(X)
# fit2 = pca.fit(X)
# print("Explained Variance: %s" % pca.explained_variance_ratio_) 
# print(fit)

In [ ]:
from sklearn.linear_model import LogisticRegression

# all parameters not specified are set to their defaults
# For small datasets, ‘liblinear’ is a good choice
logisticRegr = LogisticRegression(solver = 'liblinear')
logisticRegr.fit(X_train, y_train)

In [ ]:
# Predict for One Observation
predicted = logisticRegr.predict(X_test)
print(logisticRegr.predict(X_test))
print(y_test.index)
# df8['best_actor'][y_test.index]

In [ ]:
logisticRegr.score(X_test, y_test) # 0.6528925619834711

In [ ]:
from sklearn.metrics import confusion_matrix
tn, fp, fn, tp = confusion_matrix(y_test, predicted).ravel()
sensitivity = tp/(tp+fn)
print(sensitivity) # 0.358974358974359

In [ ]:
# Improvement: Cross Validation
# 3-fold Cross validation
from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(n_splits=3)
sumAccuracy = []
for train,test in skf.split(X,y):
#     logisticRegr.fit(df_clean.iloc[train][], )
    df_train = df_clean.iloc[train]
    df_test = df_clean.iloc[test]
    train_X = df_train[df_clean.columns.difference(['winner'])]
    train_y = df_train['winner']
    test_X = df_test[df_clean.columns.difference(['winner'])]
    test_y = df_test['winner']
    logisticRegr.fit(train_X, train_y)
    sumAccuracy.append(logisticRegr.score(test_X, test_y))
avg = np.mean(sumAccuracy)
print(avg) # 0.7803837953091683
#     print(df_clean.iloc[train,df_clean.columns.difference(['winner'])])